<?php
declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var \Unzer\PAPI\Block\Customer\CardsRenderer $block */
/** @var Escaper $escaper */

$cc = $escaper->escapeHtml($block->getNumberLast4Digits());
$brand = $escaper->escapeHtml($block->getBrand());
$exp = $escaper->escapeHtml($block->getExpDate());
$confirm = (string)__('Are you sure you want to delete this card: %1?', $cc);
?>

<div class="p-2"><?= $cc ?></div>

<div class="p-2"><?= $exp ?></div>

<div class="p-2 hidden lg:block"><?= $brand ?></div>

<div class="p-2 text-center">
    <form
            method="post"
            action="<?= $escaper->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            x-data
            x-on:submit.prevent="if (confirm($el.dataset.confirm)) $el.submit()"
            data-confirm="<?= $escaper->escapeHtmlAttr($confirm) ?>"
    >
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden"
               name="<?= \Magento\Vault\Api\Data\PaymentTokenInterface::PUBLIC_HASH ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getToken()->getPublicHash()) ?>">
        <button type="submit" style="color:#d10029">
            <span><?= $escaper->escapeHtml(__('Delete')) ?></span>
        </button>
    </form>
</div>
